# -*- coding: utf-8 -*-
"""Chapter 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m5g-9_ufffxhHP070zUUHT4roWyaCHuy
"""

# Making another list again, same as chapter 2
players = [{
   'name': 'Cooper Kupp',
   'catches': 145,
   'targets': 191
   },
   {
   'name': 'Deebo Samuel',
   'catches': 77,
   'targets': 121
   },
   {
   'name': 'Justin Jefferson',
   'catches': 108,
   'targets': 167
   },
]

# defining a function that takes in a value not really sure how this works to be honest, i think i need to review functions and get
# a better understanding of this shit. This function is defining get_catch_rate, taking the value of player. We are just defining the function here, and in the next code block we are actually creating the player list for all
# each of these variables to actually work.
def get_catch_rate(player):
    if type(player) is not dict: # if statement, type is the value of a variable, in this case the value is making sure player is not a dictionary object, passing it through
    # the loop if the type is dictionary
        print('You need to pass in a dictionary!')
        return
    else:
        pass
  # setting catches and targets to the player value from the list
    catches = player['catches']
    targets = player['targets']
  # if statement, standard just if catches > targets basically catching it to make sure it cannot run through the if statement
    if catches > targets:
        print('You can not have more catches than targets')
        return



# for player in players:
#   name = player["name"]
#   catches = player["catches"]
#   targets = player["targets"]
#   catch_rate = catches/targets
#   print(name + ' has a catch rate of ' + str(catch_rate))

player = {
    'name': 'Julio Jones',
    'catches': 99 ,
    'targets': 150
}

get_catch_rate(player)

for player in players: # for loop using the player variable we made above, in the list players. name is referencing the player["name"] part of the list. same for all the other variables.
  name = player["name"]
  catches = player["catches"]
  targets = player["targets"]
  # variable assigned to
  catch_rate = catches/targets
  print(name + ' has a catch rate of ' + str(catch_rate))